/*

 BACKGROUNDMAPSPACE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 36
   Tile set      : Z:\home\nicholas\Downloads\Gameboy Dowloads\gbtd22\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapWidth 20
#define BackgroundMapHeight 36
#define BackgroundMapBank 0

extern unsigned char BackgroundMap[];

/* End of BACKGROUNDMAPSPACE.H */
