/*

 BACKGROUNDMAPSPACE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 36
   Tile set      : Z:\home\nicholas\Downloads\Gameboy Dowloads\gbtd22\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/



unsigned char WindowMap[] =
{
  0x1D,0x0D,0x19,0x1C,0x0F,0x00,0x01,0x00,0x16,0x13,0x10,0x0F,0x00,0x04,     
};

/* End of BACKGROUNDMAPSPACE.C */
